# Generated by Django 3.1.3 on 2020-11-08 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201108_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos', verbose_name='Foto'),
        ),
    ]
