# Generated by Django 3.1.3 on 2020-11-13 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
            ],
            options={
                'verbose_name': 'Conexão',
                'verbose_name_plural': 'Conexões',
            },
        ),
        migrations.RenameModel(
            old_name='Equipments',
            new_name='Equipment',
        ),
        migrations.DeleteModel(
            name='Connections',
        ),
        migrations.AddField(
            model_name='connection',
            name='after',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='after', to='equipments.equipment'),
        ),
        migrations.AddField(
            model_name='connection',
            name='before',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='before', to='equipments.equipment'),
        ),
    ]
