# Generated by Django 3.1.3 on 2020-11-13 13:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0002_auto_20201113_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('1', 'Operacional'), ('2', 'Inoperante Parcialmente'), ('3', 'Inoperante Total')], default=0, max_length=1, verbose_name='Situação'),
            preserve_default=False,
        ),
    ]
