# Generated by Django 3.1.3 on 2020-11-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0005_auto_20201113_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('success', 'Operacional'), ('warning', 'Inoperante Parcialmente'), ('danger', 'Inoperante Total')], default=1, max_length=7, verbose_name='Situação'),
        ),
    ]
