# Generated by Django 3.1.3 on 2020-11-17 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0007_auto_20201117_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='after',
        ),
        migrations.AddField(
            model_name='connection',
            name='direction',
            field=models.CharField(choices=[('left', 'Entrada'), ('right', 'Saída'), ('exchange', 'Bi-direcional')], default='left', max_length=8, verbose_name='Direção do Tráfego'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='before',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connection', to='equipments.equipment'),
        ),
    ]
