# Generated by Django 3.1.3 on 2020-11-17 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0008_auto_20201117_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connection',
            old_name='before',
            new_name='equipment',
        ),
    ]
