# Generated by Django 3.1.3 on 2020-11-17 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0010_connection_equipment_conected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='connection',
            name='equipment_conected',
        ),
        migrations.AddField(
            model_name='connection',
            name='equipment_left',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_left', to='equipments.equipment', verbose_name='Equipamento Anterior'),
        ),
        migrations.AddField(
            model_name='connection',
            name='equipment_right',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_right', to='equipments.equipment', verbose_name='Equipamento Posterior'),
        ),
    ]
