# Generated by Django 3.1.2 on 2020-10-28 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20201020_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='protcol',
            new_name='protocol',
        ),
    ]
