# Generated by Django 3.1.2 on 2020-11-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_auto_20201029_1753'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'ordering': ['id'], 'verbose_name': 'Ação', 'verbose_name_plural': 'Ações'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['id'], 'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
        migrations.AlterField(
            model_name='action',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='action',
            name='description',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='action',
            name='short_description',
            field=models.CharField(max_length=50, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='action',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Alterado em'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='short_description',
            field=models.CharField(max_length=50, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Alterado em'),
        ),
    ]
