# Generated by Django 3.1.2 on 2020-11-06 12:36

from django.db import migrations, models
import tickets.utils


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_auto_20201106_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='docfile',
            field=models.FileField(null=True, upload_to=tickets.utils.path_and_rename, verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='docfile',
            field=models.FileField(null=True, upload_to=tickets.utils.path_and_rename, verbose_name='Arquivo'),
        ),
    ]
