# Generated by Django 3.1.3 on 2020-11-09 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_auto_20201109_0202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='group',
        ),
    ]
