# Generated by Django 3.1.3 on 2020-11-09 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        ('tickets', '0014_remove_ticket_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='teams',
            field=models.ManyToManyField(related_name='tickets', to='teams.Team'),
        ),
    ]
