# Generated by Django 3.1.3 on 2020-11-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_auto_20201109_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='time',
            field=models.IntegerField(verbose_name='Tempo Utilizado'),
        ),
    ]
