# Generated by Django 3.1.3 on 2020-11-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0017_auto_20201110_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='time',
            field=models.IntegerField(default=0, verbose_name='Tempo Utilizado'),
        ),
    ]
