# Generated by Django 3.1.3 on 2020-11-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0018_auto_20201110_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='time',
            field=models.IntegerField(default=0, null=True, verbose_name='Tempo Utilizado'),
        ),
    ]
