# Generated by Django 3.1.3 on 2020-11-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0020_auto_20201111_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='teste',
            field=models.DateTimeField(auto_now=True, verbose_name='Alterado em'),
        ),
    ]
