# Generated by Django 3.1.3 on 2020-11-11 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0021_ticket_teste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='teste',
        ),
    ]
