# Generated by Django 3.1.3 on 2020-11-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0022_remove_ticket_teste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='time',
            field=models.IntegerField(default=0, verbose_name='Tempo Utilizado'),
        ),
    ]
