# Generated by Django 3.1.3 on 2020-11-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0005_auto_20201113_1334'),
        ('tickets', '0023_auto_20201111_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='equipment',
            field=models.ManyToManyField(related_name='tickets', to='equipments.Equipment'),
        ),
    ]
