# Generated by Django 3.1.3 on 2020-11-17 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0025_auto_20201116_1240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-id'], 'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
    ]
